// Exportar todos los componentes comunes desde un solo lugar
export { default as Button } from './Button'
export { default as Input } from './Input'
export { default as Card } from './Card'
export { default as Alert } from './Alert'
export { default as Spinner } from './Spinner'
export { default as Badge } from './Badge'
export { default as ProtectedRoute } from './ProtectedRoute'
export { default as ErrorBoundary } from './ErrorBoundary'
export { default as TestConnection } from './TestConnection'
export { default as Modal } from './Modal'
export { default as Pagination } from './Pagination'
export { default as FirmaCanvas } from './FirmaCanvas'
export { default as TerminosYCondiciones } from './TerminosYCondiciones'

